### ISSUE TITLE
practicalmeteor no longer works with 1.6 - should not be recommended

### ISSUE THREAD

**Issue by davidworkman9** [meteor/guide#672] opened 2017-11-01 19:33 UTC
`practicalmeteor:mocha` is recommended in the Meteor guide, although it no longer works as of 1.6. It appears that `meteortesting:mocha` is considered best practice now.

**Comment by abernix** [comment] 2017-11-04 20:43
Thanks for reporting this!  I'm fairly confident that you're right, and that they're API-compatible with each other.  Would you be able to submit a pull request with that change?

**Comment by abernix** [comment] 2017-11-27 09:28
@davidworkman9 Any update on this?

**Comment by davidworkman9** [comment] 2017-11-27 13:31
It seems that updating coffeescript fixes `practicalmeteor:mocha` so I went back to it. API wise I think they're the same, all my tests worked. The differences I could tell were that `practicalmeteor:mocha` ran faster and had a clean web interface where you could see the results of both the server and client tests. `meteortesting:mocha` dumps the server tests to the terminal, without any colour coding.

**Comment by znewsham** [comment] 2017-12-05 13:59
@davidworkman9 what did you update coffeescript from/to? I'm still having this error, and it exists with `meteortesting:mocha` too

**Comment by davidworkman9** [comment] 2017-12-05 14:09
I ran `meteor update coffeescript` in my project directory. Resulted in this diff:

```
-coffeescript@1.0.17
+coffeescript@1.12.7_3
+coffeescript-compiler@1.12.7_3
```

**Comment by znewsham** [comment] 2017-12-05 14:42
@davidworkman9 thanks, sadly I'm already on those versions :(

**Comment by davidworkman9** [comment] 2017-12-05 14:51
@znewsham Have you came across this [issue](https://github.com/practicalmeteor/meteor-mocha/issues/94)? There's a comment on there that also recommends using `practicalmeteor:mocha@2.4.5_6`.

**Comment by znewsham** [comment] 2017-12-05 14:55
@davidworkman9 I hadn't seen that, but unfortunately it doesn't help, I'm already on those versions. My issue seems to relate to either acorn or escodegen missing binaries - though I don't use either of those packages directly, I assume they are required by one of the packages I use (or Meteor core?)

**Comment by abernix** [comment] 2017-12-05 15:06
@znewsham Have you made sure to remove your `node_modules` directory and re-install with `meteor npm install` after the upgrade to Meteor 1.6?  Alternatively, you could try `meteor npm rebuild`.

In addition, I'd try a `meteor reset` (Which will wipe your development DB!). The Node version has changed and some older binaries lying around in `node_modules` could be causing a problem.

**Comment by znewsham** [comment] 2017-12-05 15:09
@abernix, yes I did that - I have some other NPM packages that use binaries (canvas, etc) so I had to npm install to get those working. I tried a reset about 10 mins ago, but that only impacts the project, correct - not the packages? Just to clarify - my issues is about testing a local package

**Comment by abernix** [comment] 2017-12-05 16:24
@znewsham Let's take this conversation back to https://github.com/meteor/meteor/issues/9438.  If you could make a reproduction there and provide more detailed error messages, that'd help with finding you a solution.   Though, whatever we figure out eventually over there, should contribute to the solution for this issue here.

**Comment by serut** [comment] 2018-05-09 15:52
I've just finished to switch [meteor-coverage](https://github.com/serut/meteor-coverage) from practicalmeteor dependencies (chai, spacejam, mocha...) to meteortesting and real npm dependencies. Everything looks good and run much faster than in Meteor 1.3.

However, there is still an issue with meteor packages and NPM dependencies, a solution is to use an empty Meteor app if you have any trouble : 
```
# Before tests
$ rm -rf ./someapp &&
  meteor create --bare someapp &&
  cd someapp && 
# Install some dependency unavailable in your test if you are not inside a meteor app
  meteor npm i --save selenium-webdriver@3 chromedriver && 
  mkdir packages &&
  ln -s ../../ ./packages/meteor-coverage
```
It was just an illustration of the bullshit that still exists with Meteor 1.6.1 test mode. So please, stop mentionning practicalmeteor in the official guide, meteortesting is already way better than practicalmeteor.

**Comment by StorytellerCZ** [comment] 2018-05-30 12:31
#691

**Comment by filipenevola** [comment] 2021-02-03 13:51
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.

**Closed by filipenevola** 2021-02-03 13:51 UTC
